"""Re-downloads the Google Fonts used by the flyers into flyers/shared/fonts and rewrites flyers/shared/fonts.css.
Run once (or when adding a family); the woff2 files are committed so rendering never depends on network."""
import re, subprocess, os
UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36"
families = ["Baloo+2:wght@600;700;800","Nunito:wght@500;600;700;800;900","Montserrat:wght@500;900",
            "Anton","Space+Grotesk:wght@400;500;600;700","Lilita+One","Fredoka:wght@500;600;700",
            "Instrument+Serif:ital@0;1","Inter:wght@400;500;600;700"]
ROOT = os.path.join(os.path.dirname(__file__), "..", "shared")
os.makedirs(os.path.join(ROOT, "fonts"), exist_ok=True)
url = "https://fonts.googleapis.com/css2?" + "&".join("family="+f for f in families) + "&display=swap"
css = subprocess.check_output(["curl","-sS","--max-time","30","-A",UA,url]).decode()
out = ["/* Fonts bundled locally so headless/print renders never depend on network. Generated by flyers/export_tool/fetch_fonts.py */"]
for subset, block in re.findall(r"/\*\s*(\w+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css):
    if subset != "latin": continue
    fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
    wt = re.search(r"font-weight:\s*(\d+)", block).group(1)
    if re.search(r"font-style:\s*italic", block): wt += "i"
    src = re.search(r"url\(([^)]+)\)", block).group(1)
    fname = re.sub(r"[^A-Za-z0-9]+","_",fam) + f"_{wt}.woff2"
    path = os.path.join(ROOT, "fonts", fname)
    if not os.path.exists(path):
        subprocess.check_call(["curl","-sS","--max-time","60","-A",UA,"-o",path,src])
    block = re.sub(r"src:[^;]+;", f"src: url('fonts/{fname}') format('woff2');", block)
    block = re.sub(r"\s*unicode-range:[^;]+;", "", block)
    out.append(block)
open(os.path.join(ROOT, "fonts.css"), "w").write("\n".join(out)+"\n")
print("wrote fonts.css")
